theme: jekyll-theme-cayman
title: <img src="pic.png" width="200"/> \n Jinghao Sun
description: Email: jinghao.sun@yale.edu
description: Twitter: @JHSun5
email: jinghao.sun@yale.edu
name: Jinghao Sun's homepage
